# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            R
tagline:          "J'aime les bananes"
description:      'R Course.'
url:              https://emanuelhuber.github.io/Rcourse/
baseurl:          /Rcourse

#author:
#  name:           'Mark Otto'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
